### ISSUE TITLE
Parsing other groups and storing in dictionary

### ISSUE THREAD

**Issue by cth7** [pehses/twixtools#1]
Hi. Recently found your repository and am interested in using it to load Siemens MRI raw data. Are there any plans to parse the other groups (e.g. 'Dicom') using [parse_ascconv](https://github.com/mrphysics-bonn/twixtools/blob/master/twixtools/twixprot.py#L78)? Currently only 'MeasYaps' is parsed and stored as a dictionary. It would be useful if the other groups could be parsed and values stored in dictionaries too.

I tried adding the names of the other groups [here](https://github.com/mrphysics-bonn/twixtools/blob/master/twixtools/twixprot.py#L163) as such

```python
if name in ['Config', 'Dicom', 'Meas', 'MeasYaps', 'Phoenix', 'Spice']:
```

but I encounter an error. Was wondering if the others could be parsed in similar fashion or if different logic is required?

**Comment by pehses** [comment]
This should work now after the recent (huge!) commit should.
