### ISSUE TITLE
Error when calculating rotation matrix

### ISSUE THREAD

**Issue by schmidtijoe** [pehses/twixtools#16]
Hi all,
I think i've found a mistake in the calculation of the rotation matrix in:
https://github.com/pehses/twixtools/blob/08cc6b7a8b16570b35e0691a20b839b53137b2af/twixtools/geometry.py#L124

The mathematical operation `V * V` gives a matrix with squared entries, while what we actually need there is a matrix multiplication (i.e. `np.matmul(V, V)`. The resulting rotation matrix otherwise is errorous and not orthonormal.

**Comment by pehses** [comment]
Should be fixed by merge of pull request #17 from schmidt-jo/fix_rot_mat
