### ISSUE TITLE
Small indent error

### ISSUE THREAD

**Issue by Nils-N** [pehses/twixtools#3]
Hey, 

First of all thanks for making this tool available - this will save me a lot of time at the scanner and at postprocessing.  

I believe in twixzip.py , line 705 there is an indent error 
parser.add_argument("--profile", action="store_true")

(Otherwise args.profile is not defined in the --decompress mode and it crashes at line 709)

**Comment by pehses** [comment]
Thanks! I think this bug should be fixed in the latest (huge!) commit.
